root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

# templ generate -watch -proxy="http://localhost:8888"
# -cmd="wgo -file .go go run ./cmd/server :: curl -XPOST 'http://localhost:7331/_templ/reload/events'"
[build]
  args_bin = []
  bin = "./tmp/server.exe"
  pre_cmd = []
  cmd = "go build -o ./tmp/server.exe ./cmd/server"
  post_cmd = []
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", ".idea"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  rerun = true
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = true

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
